### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#51] opened 2022-10-05 14:00 UTC
**Describe the bug**
As node operator i cannot apply for less than 3024 etny from marketplace 

**To Reproduce**
1. Go to Marketplace
2. Try to apply for less then 3024 etny
43 See error

**Expected behavior**
If in marketplace are offers with less then 3024 etny nowone can apply, so are locked

**Comment by varvarasd** [comment] 2022-10-06 06:19
Hi,
This is the expected behavior. The minimum extended staking amount is 3024 ETNY. Please find all these details in the documentation [here](https://docs.ethernity.cloud/staking-dapp/intro).
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-06 06:19 UTC
Labels: bug

**Comment by pupisor** [comment] 2022-10-06 06:33
ok....but if someone have less then 3024 etny he can't stake it right?

**Comment by varvarasd** [comment] 2022-10-06 07:33
The minimum extended staking amount is 3024 ETNY. You cannot create or apply to an extended stake less than 3024 ETNY.
