### ISSUE TITLE
BUG Error -

### ISSUE THREAD

**Issue by Mssaytek** [ethernity-cloud/ethernity-staking-dapp#10] opened 2022-09-30 15:06 UTC
**Describe the bug**
When I make a request for the extended staking an erros shosw to "Node wallet adress"

**To Reproduce**
1. Go to 'New Stake'
2. Click on 'Staking request type'
3. Scroll down to 'Extended staking'
4. Introduce the details
5. See the error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
![Screenshot 2022-09-30 at 18 01 43](https://user-images.githubusercontent.com/114657660/193300039-79467247-2903-4cc9-b3b3-41b6287bde2f.png)

 - OS: macOS Monterey
 - Browser [Brave]

**Additional context**

**Bug-bounty required information (optional)**
Please provide your email address if you wish to join the bug-bounty

**Comment by dim3nsi0n32** [comment] 2022-09-30 15:20
Hi, node address shouldn't have any tETNY tokens in it for security reasons. You are trying to delegate your extended stake to a node which has tokens in it already. 
Please read the staking rules at https://docs.ethernity.cloud/staking-dapp/staking-rules

**Comment by Mssaytek** [comment] 2022-09-30 15:22
Ok, thanks. How can I totally remove tETNY token from metamask node wallet? I tried hide but shows same problem.

**Comment by dim3nsi0n32** [comment] 2022-09-30 21:00
you need to send your tETNY from this wallet to a different wallet address so this wallet will only have 0 tENTY. You could send it to the staker wallet address.

**Comment by Mssaytek** [comment] 2022-09-30 21:14
I have try that multiple times. Is failing to send them. I am stuck with tETNY in node wallet :(

**Comment by varvarasd** [comment] 2022-10-03 06:53
Hi. For testing purposes, you can use any clean wallet address with no tokens. The simplest way is to create a new one in Metamask. 

I will close this as it's not a bug

**Closed as completed by varvarasd** 2022-10-03 06:53 UTC
Labels: bug
