### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Yaroslavyy** [ethernity-cloud/ethernity-staking-dapp#35] opened 2022-10-02 15:16 UTC
**You cannot send tokens from wallet to wallet. If it mistakenly sends tokens to the node, it does not allow you to connect as an operator if the tokens are in the account.**

1. Go to (https://staking.ethernity.cloud/staking)
2. Click on MetaMask
3. See error

**Expected behavior**
The ability to transfer from wallet to wallet, these are test tokens

**Screenshots**
![image](https://user-images.githubusercontent.com/95451597/193461560-820151a9-369d-4498-9055-447675e1c2bc.png)
![image](https://user-images.githubusercontent.com/95451597/193461574-032e9998-d295-4e58-8d79-0d1d0b03e17a.png)

**Desktop **
 - OS: windows 10
 - Browser: chrome

e-mail: y.o.yasinskiy@gmail.com

**Comment by varvarasd** [comment] 2022-10-03 12:45
Hi,
This is the expected behavior. It shouldn't be a blocker for any tester. We are considering adding this ability for testing purposes. You can use any other wallet with 0 tETNY to connect as an operator.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-03 12:45 UTC
Labels: bug
