### ISSUE TITLE
Propunere

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#33] opened 2022-10-02 10:30 UTC
![Screenshot from 2022-10-02 12-29-08](https://user-images.githubusercontent.com/25704511/193449546-6fd72b64-63bd-40d6-b6b0-5654ffb43b54.png)
Aici ar fi bine sa mai fie un block cu rewards! Si block-ul cu total tokens nu cred ca isi are rost atata timp cat nu sunt tokeni pe nod!

**Comment by varvarasd** [comment] 2022-10-03 12:36
Hi,
We are not taking any feature suggestions at this time as it's not a priority, however, thank you.
In the future, for your bug report to be addressed please make sure you use the default bug reporting format and fill it in accordingly.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-03 12:36 UTC
Labels: bug
