### ISSUE TITLE
Scroll/Hidden text BUG

### ISSUE THREAD

**Issue by rockydawe** [ethernity-cloud/ethernity-staking-dapp#47] opened 2022-10-04 11:33 UTC
**Hidden text **
After scrolling down the Page, remains a half hidden text.

**To Reproduce**

1. Log in with metamask wallet
2. STAKING OVERVIEW -> Click on 'Approved'
3. Click on either one of the Staking Offers showed , on ''Details''
4. Either clicking on ''Peneding'' or ''Terminated'' after scrolling down to the bottom of the page, it remains half text hidden.

**Expected behavior**
The text needs to be completely Visible.

**Screenshots**

https://user-images.githubusercontent.com/114801900/193809322-f401d557-ca38-44a3-ad24-807ecb2d433a.mp4

**Desktop (please complete the following information):**

 - Browser  Google Chrome

**Additional context**

**Bug-bounty required information (optional)**
fluerasdavid@yahoo.com

**Comment by varvarasd** [comment] 2022-10-04 11:51
Hi,
The bottom banner exists only in testing and it's not included in the production build therefore this is not a bug.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 11:51 UTC
Labels: bug

**Comment by rockydawe** [comment] 2022-10-04 12:02
I read that we should find bugs in the testnet, things that are not working/showing as expected. That's what I did. If you think that is ok and well done, what should I say, you're the expert.
