### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Dontyouseeme** [ethernity-cloud/ethernity-staking-dapp#13] opened 2022-09-30 17:48 UTC
![eroare selectare procent](https://user-images.githubusercontent.com/61425685/193328547-5569fb3a-122e-4425-ac47-8ce3d35a37dd.jpg)

Hello there,
I`ve been trying to create a base stake but, I cannot select the proccent! I suposed I should be able to choose it.. on another account with the same settings it`s allow me to do so..

**Comment by dim3nsi0n32** [comment] 2022-09-30 20:57
A base stake reward will always go do the operator. The operator gets 100% of the reward. An extended stake on the other hand can be split between staker and node operator and the staker decides the split. Just change the Staking request type from Base staking to Extended Staking and you'll see what I mean. This is not a bug.

**Comment by varvarasd** [comment] 2022-10-03 06:59
I will close it as it's not a bug. Please read the documentation carefully [here](https://docs.ethernity.cloud/staking-dapp/intro).

**Closed as completed by varvarasd** 2022-10-03 06:59 UTC
Labels: bug
