### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dimanyo** [ethernity-cloud/ethernity-staking-dapp#19] opened 2022-10-01 16:38 UTC
**Describe the bug**
eternal loading at the entrance to the office. 

**To Reproduce**
1. Go to 'connect wallet'
2. Click on
3. See error

**Screenshots**
Will be in the video

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser chrome

**Additional context**
Eternal loading is solved by reloading the page

https://user-images.githubusercontent.com/114760279/193419325-a9ab54cb-861a-4e9a-9ef9-1383780ab3fe.mp4

**Comment by varvarasd** [comment] 2022-10-04 09:57
Hi,
In the future please report only in English, including the text in the recording to be able to investigate and address properly the issue.
This is a limitation of MetaMask. It appears you need to go back to metamask, after confirming the network change, to confirm the tETNY token addition. This feature is available only in testing as it will not be part of the production.
I will close this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 09:57 UTC
Labels: bug
