### ISSUE TITLE
How to use this for a polygon token

### ISSUE THREAD

**Issue by motikolorado** [ethernity-cloud/ethernity-staking-dapp#49] opened 2022-10-04 19:27 UTC
Is it possible to change some things in the files so as to use this dapp for staking polygon token? If so please what should be changed. And how do i deploy the contract?

**Comment by varvarasd** [comment] 2022-10-05 06:35
Hi,
The Ethernity Cloud Staking dApp is only for ETNY staking. There are no plans at this time to stake other tokens than ETNY.
Please note this is a place for BUG REPORTING. If you have any questions please use our [telegram](https://t.me/ethernitycloud) or [discord](https://discord.gg/W74JcFPGcb) channels.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-05 06:35 UTC
