### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dimanyo** [ethernity-cloud/ethernity-staking-dapp#53] opened 2022-10-05 17:27 UTC
**Describe the bug**
In the new bet, I indicate that no approval is required, but the bet is still placed with approval

**To Reproduce**
1. Go to 'NEW STAKE'
2. Click on 'Is staking pot pre-approved? NO'
4. APPROVAL NEEDED YES on the marketplace

Watch the video, you'll understand what I'm talking about

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome

https://user-images.githubusercontent.com/114760279/194125602-b9e3431e-6930-4a5b-a0aa-3598920f8948.mp4

**Bug-bounty required information (optional)**
Dimanyo1@yandex.ru

**Comment by varvarasd** [comment] 2022-10-06 08:31
Hi, this is the expected behavior. The pot is not pre-approved as you indicated 'NO' on the toggle instead of 'YES' therefore it requires approval.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-06 08:31 UTC
Labels: bug
