### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RodmannNftArt** [ethernity-cloud/ethernity-staking-dapp#23] opened 2022-10-01 22:23 UTC
**Describe the bug**
Cannot add a POT on marketplace even if the value is lower than the remaining amount allowed on a node.
Actual staked on the node 72924 ETNY 

![IMG_5354](https://user-images.githubusercontent.com/98767703/193430109-eb4da226-c073-4211-8b90-96d97ad097ee.jpg)
and tried to apply for a pot (POT 005) with 953 ETNY

![IMG_5353](https://user-images.githubusercontent.com/98767703/193430165-b3009b7b-71e2-4e0e-ba53-e4906fd1f8b7.jpg)
![IMG_5357](https://user-images.githubusercontent.com/98767703/193430168-df19603c-a11a-40b4-865a-40dd2a8b8461.jpg)

I receive the following error message: "The amount is lower than min extended stake value"

**Expected behavior**
I assume if 72924 ETNY total stake on the node, it remains 2076 available (up to max limit of 75000 ETNY) 
Adding 953 ETNY would remain free for staking another 1123 ETNY

**Desktop **
 - OS: Windows 10
 - Browser Firefox 105.0.1 (64-bit)

**Comment by varvarasd** [comment] 2022-10-03 10:40
Thank you. We are adding this to our backlog for a fix.

**Comment by varvarasd** [comment] 2022-10-03 11:39
Hi, thank you. This is the expected behavior.
I will close this as not a bug.

**Closed as completed by varvarasd** 2022-10-03 11:39 UTC
Labels: bug
