### ISSUE TITLE
BUG / not refinement.

### ISSUE THREAD

**Issue by shikter** [ethernity-cloud/ethernity-staking-dapp#57] opened 2022-10-14 10:13 UTC
**Describe the bug**

Some issues:
1. For several days, the process of stacking progress is not visible. How much and where you can see the number of stacking progress; Or predictable. (In the number of coins or in % ratio of the amount that was/will stacked.)

2. I have had 2 test accounts as Client stackers and 1 test account as Node.
In one of three cases, I could withdraw rewards to the Node wallet. (Is it right? Or shouldn't it be) (Partly already fixed by date 14.10.22)

3. When entering ETNY, the price always flips to another number… (Last time I realized that this bug had already been fixed).

4. If you have multiple nodes, you can specify the wallet of another node. (Is it correct? Or in node wallet at all shouldn't come any ETNY?) What will happen if ETNY comes to the node's wallet?

5. If you do stuffing into the market, as an offer. That Rewards wallet, you can specify as your Node. (Is it correct?)

A request for 5000ETNY was sent to the market, the node operator could only take 4500, and I confirmed. The question remains, where does the 500 etny go? Because it shows that it is staking too. (Not available somewhere). (And the same time using only 4500 ETNY for stacking...)

**Screenshots**
[Screen1](https://drive.google.com/file/d/16iRvatm63HyYnHqJ3xfgSQdMJcoi_tXZ/view?usp=sharing)
[Screen2](https://drive.google.com/file/d/1EHngxfjs44wyoBIeb_y4YvSVO4wh-MVE/view?usp=sharing)
[Screen3](https://drive.google.com/file/d/13_L4J5krxPgF3mDETZfqmTAK6ieZQOXU/view?usp=sharing)
[Screen4](https://drive.google.com/file/d/1D2I-PA8FEzwRFtanwUsdM8EmSE1MPc1-/view?usp=sharing)
[Screen5](https://drive.google.com/file/d/1TP8gLGS6jmWuvirmSONbSH_E_irOC1Ge/view?usp=sharing)
[Screen6](https://drive.google.com/file/d/1mSuuTxl0L7WhDYrD2N-vefmbEhlf6HQl/view?usp=sharing)
[Screen7](https://drive.google.com/file/d/1UFDniyjgHzx2e_UX6tuX8CHKJMTS6dU-/view?usp=sharing)
[Screen8](https://drive.google.com/file/d/17xtqxPM5wYta-EUqCksOhgv16fUrY3PS/view?usp=sharing)
[Screen9](https://drive.google.com/file/d/1oFXwoA5LqXS405sglR2KSvZqfpo7bAZi/view?usp=sharing)
[Screen10](https://drive.google.com/file/d/1uIDaVqqirHhua4XaZ2p3Q34Ruv8xhx_C/view?usp=sharing)
[Screen11](https://drive.google.com/file/d/1_IXte-G7h0UUEkbCVMpCzPxt57HvFYvI/view?usp=sharing)
[Screen12](https://drive.google.com/file/d/1SB9PwY7i9n0wgQ8_Fugz4A5RnWql1SdT/view?usp=sharing)

MetaMask wallet as well not showing something about lock / sent TETNY. (Should it be like that?

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome 

**Bug-bounty required information (optional)**
rypy91@gmail.com

**Comment by varvarasd** [comment] 2022-10-14 11:48
Hi,

It is very hard to understand what is going on. To be able to address this, please split it into each individual bugs and fill out the default bug reporting form accordingly so we can reproduce. I will leave the default reporting form below for your consideration.

Please note that this will not be taken into account and it will be closed as unable to reproduce.

Thank you


**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]


**Additional context**
Add any other context about the problem here.

**Bug-bounty required information (optional)**
Please provide your email address if you wish to join the bug-bounty

**Closed as not planned** 2022-10-17 07:22 UTC
Labels: bug
