### ISSUE TITLE
BUG?

### ISSUE THREAD

**Issue by Mssaytek** [ethernity-cloud/ethernity-staking-dapp#11] opened 2022-09-30 15:14 UTC
**Describe the bug**
After I manage to introduce all details for staking an erros appears with the message: xEthernity The node doesen't have any base stake setup!

**To Reproduce**
1.Introduce details for staking
2. Review Stake
3. Agree
4. Error appear

**Screenshots**
![Screenshot 2022-09-30 at 18 05 41](https://user-images.githubusercontent.com/114657660/193301636-ea805ff8-7614-435b-99ce-5f2b03deda1b.png)

**Desktop (please complete the following information):**
 - macOS Monterey
 - Browser; Brave

**Additional context**

**Bug-bounty required information (optional)**
Please provide your email address if you wish to join the bug-bounty

**Comment by dim3nsi0n32** [comment] 2022-09-30 15:17
Please check the documentation on how to approve a base stake request https://docs.ethernity.cloud/staking-dapp/base-stake/approve-base-stake
After you create a base stake as a staker, you have connect the wallet from your node to approve it. Only then your node can apply for extended stake requests.

**Comment by varvarasd** [comment] 2022-10-03 06:54
I will close this as not a bug.

**Closed as completed by varvarasd** 2022-10-03 06:54 UTC
Labels: bug
