### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by MSorin5** [ethernity-cloud/ethernity-staking-dapp#40] opened 2022-10-03 06:10 UTC
**Describe the bug**
Incorrect button appears logged in as staker

**Expected behavior**
The command button should appear in clear. [LINK](https://staking.ethernity.cloud/staking/121?type=2)

**Screenshots**
![bug-buton](https://user-images.githubusercontent.com/97909102/193511021-45da37d3-f633-4b33-a588-64605f7f71e1.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome

**Bug-bounty required information (optional)**
sorinweb3@gmail.com

**Comment by varvarasd** [comment] 2022-10-04 08:27
Hi,
I am not able to reproduce this. Please can you tell us step by step what you are doing?

**Comment by MSorin5** [comment] 2022-10-04 08:44
Now I see that button B no longer appears, it is Cancel Tab

**Comment by varvarasd** [comment] 2022-10-04 09:01
I am closing this as not a bug as we're unable to reproduce it.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 09:01 UTC
Labels: bug
