### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#29] opened 2022-10-02 08:25 UTC
![Screenshot from 2022-10-02 10-24-31](https://user-images.githubusercontent.com/25704511/193445078-3185c5d8-21a0-4028-9137-e6dfe1f914c2.png)
Cannot apply for lower than 3024 Etny ... so small amouts from marketplace are locked

**Comment by pupisor** [comment] 2022-10-02 11:13
de exemplu daca cineva are 1976 etny nu ii va putea delega pe nici un nod, atata timp cat minimul e 3024 pentru acceptare in extended...sper ca m-am facut inteles

**Comment by varvarasd** [comment] 2022-10-03 12:07
Hi,
In the future, for your bug report to be addressed please make sure you use the default bug reporting format and fill it in accordingly.
This is the expected behavior. The staker can withdraw the remaining tokens and create other pots. 
I am closing this as not a bug.
Thank you

**Closed as completed by varvarasd** 2022-10-03 12:07 UTC
Labels: bug
