### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Yaroslavyy** [ethernity-cloud/ethernity-staking-dapp#34] opened 2022-10-02 14:54 UTC
"The cross does not work in order to remove the running line. If the running line should not be removed, then it is not clear why the cross."

**To Reproduce**
1. Go to (https://staking.ethernity.cloud/staking)
2. Click on 'cross'
3. See error

"The cross should work or remove it from the display"
![image](https://user-images.githubusercontent.com/95451597/193460601-0d17d5fa-9b43-4cef-9c79-5979ea988e41.png)

**Desktop **
 - OS: windows 10
 - Browser: chrome

e-mail: y.o.yasinskiy@gmail.com

**Comment by varvarasd** [comment] 2022-10-03 12:38
Hi, 
This is the expected behavior for testing. The banner will be entirely removed when we are releasing the production build.
I am closing this as not a bug.
Thank you.

**Closed as not planned by varvarasd** 2022-10-03 12:38 UTC
Labels: bug
