### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Cristicyb** [ethernity-cloud/ethernity-staking-dapp#48] opened 2022-10-04 12:22 UTC
**Describe the bug**
TOTAL STAKED amount of tokes DOES NOT MATCH Approved staking pots values

**To Reproduce**
Do multiple staking actions followed by Cancelling a part of the Staking pots

**Expected behavior**
TOTAL STAKED amount of tokes MATCHES Approved staking pots values

**Screenshots**
![staking_ethernity_cloud_1](https://user-images.githubusercontent.com/55314278/193817825-b3581ee6-aa25-4f13-b127-b2b4cb8bfb76.JPG)
![staking_ethernity_cloud_2](https://user-images.githubusercontent.com/55314278/193817841-0409b4bd-db65-43ad-8fe9-36270bcb7caf.JPG)
![staking_ethernity_cloud_3](https://user-images.githubusercontent.com/55314278/193817855-32d5947b-7506-4e1c-8fff-3ca01db63a61.JPG)
![staking_ethernity_cloud_4](https://user-images.githubusercontent.com/55314278/193817856-56db1c81-d445-46d1-8182-9ab107f3f7c5.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
![staking_ethernity_cloud_5](https://user-images.githubusercontent.com/55314278/193817861-eeff4a8a-4e77-453c-b3a7-325405ee4223.JPG)

**Comment by varvarasd** [comment] 2022-10-04 13:15
Hi,
There is a warning message when canceling a pot with approved and signed contracts, that says that the cancelation of said contracts is due at the end of the staking contract maturity. If you take that into account the amounts should be correct.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 13:15 UTC
Labels: bug
