### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#26] opened 2022-10-02 08:07 UTC
![Screenshot from 2022-10-02 10-04-51](https://user-images.githubusercontent.com/25704511/193444417-6b28f4bc-f2e2-49f8-b544-0540de3cf262.png)
Trehe are 2 DETAILS button on every staking pot

**Comment by varvarasd** [comment] 2022-10-03 11:49
Hi, thank you.
This has already been reported and I'll close it as a duplicate of [#14](https://github.com/ethernity-cloud/ethernity-staking-dapp/issues/14) 
In the future, if you'd like your report to be considered use the default and correct reporting format which appears by default and fill in the sections accordingly.

**Closed as completed by varvarasd** 2022-10-03 11:49 UTC
Labels: bug
