### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#28] opened 2022-10-02 08:15 UTC
I cannot apply for new offer from marketplace lower then 3024 etny , even if i am ollready on extended staking with more than 10k etny....
![Screenshot from 2022-10-02 10-14-26](https://user-images.githubusercontent.com/25704511/193444728-9751f317-725d-4374-b7ed-491c0867d09a.png)

**Comment by pupisor** [comment] 2022-10-02 11:25
deci cei care au 1976 etny in wallet nu au cum sa ii delege pe alte noduri avand in vedere ca suma minima e de 3024 ! sper ca m-am facut inteles

**Comment by varvarasd** [comment] 2022-10-03 12:05
Hi,
In the future, for your bug report to be addressed please make sure you use the default bug reporting format and fill it in accordingly.
This is the expected behavior.
I am closing this as not a bug.
Thank you

**Closed as completed by varvarasd** 2022-10-03 12:05 UTC
Labels: bug
