### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#31] opened 2022-10-02 09:28 UTC
In marketplace ar trebui sortate ofertele in functie de tokeni , active sau inactive , procent ... etc

**Comment by varvarasd** [comment] 2022-10-03 12:25
Hi,
We are not taking any feature suggestions at this time as it's not a priority, however, thank you.
In the future, for your bug report to be addressed please make sure you use the default bug reporting format and fill it in accordingly.
I am closing this as not a bug.
Thank you

**Closed as completed by varvarasd** 2022-10-03 12:25 UTC
Labels: bug
