### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by pupisor** [ethernity-cloud/ethernity-staking-dapp#32] opened 2022-10-02 09:39 UTC
Another one...nu se pot vedea tranzactiile in poligonscan...

**Comment by varvarasd** [comment] 2022-10-03 12:33
Hi,
Please make sure you use the default bug reporting format and fill it in accordingly and give as many details as possible so we can reproduce, verify or inspect the issue.
You can check [here](https://mumbai.polygonscan.com/) the transactions.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-03 12:33 UTC
Labels: bug
