### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RaduGuce** [ethernity-cloud/ethernity-staking-dapp#50] opened 2022-10-05 13:09 UTC
Hello,

I'm a node operator and after i apply for 6000 of etny in the marketplace, the amount of etny in " total staked on node" is not correlated with the amount of etny in " approved"  tab.

Aso in "pending" it show 10000 etny instead of 6000 etny. 

Thank you! 
![IMG_20221005_154945](https://user-images.githubusercontent.com/115086273/194068047-88506b09-a89d-4b36-98a8-d8d3f4a72a0a.jpg)
![IMG_20221005_154938](https://user-images.githubusercontent.com/115086273/194068084-b08da55d-bcd0-4ed9-8442-e48c6ccdfcec.jpg)
![IMG_20221005_154932](https://user-images.githubusercontent.com/115086273/194068106-328b1fc5-9b15-4b5d-a412-7cadb66a34b7.jpg)

**Comment by varvarasd** [comment] 2022-10-06 06:14
Hi,
In the future, for your bug report to be addressed please make sure you use the default bug reporting format and fill it in accordingly.
Please check the Closed tab as well. That's where you'll see any closed (closed auto-renewal) pots. These pots are also taken into account as they are staked on the node until the contract matures and adds to the total.

**Comment by RaduGuce** [comment] 2022-10-06 06:23
The Closed tab is empty.

**Comment by RaduGuce** [comment] 2022-10-06 06:32
In " Pending " i have 10000 etny , after i go to details i see approved 4000 and pending 6000.
That means that my " total staked on node" should be 14000 not 16000.

**Comment by varvarasd** [comment] 2022-10-06 06:55
I am unable to reproduce this and we need to see exactly the circumstance and steps to reproduce. We need to look at this more closely. Please send me your email address so I can get in touch and arrange a meeting with share screen and investigate this more closely if that's alright with you.

**Comment by RaduGuce** [comment] 2022-10-06 07:09
This is my pending tab and closed tab is empty
![image](https://user-images.githubusercontent.com/115086273/194236915-d6849b41-49c2-4721-ada3-21c8ff4cde29.jpeg)
![image](https://user-images.githubusercontent.com/115086273/194236995-7a4aa149-eba2-497c-afe6-9f588a1a428e.jpeg)
![image](https://user-images.githubusercontent.com/115086273/194237419-ad1c050a-cac3-43e0-b1c4-aac4daee5c7d.jpeg)

**Comment by varvarasd** [comment] 2022-10-06 08:11
Please provide the email address to schedule a video call to investigate. I cannot tell from the images if you're a staker or a node op in any of them.

**Comment by RaduGuce** [comment] 2022-10-06 10:13
Yes , i'm a node operator .

After i analyzed more ,it looks like the amount from pending contract goes to "total staked on node". 

![image](https://user-images.githubusercontent.com/115086273/194287472-f7e6d71c-6475-4cfa-84b8-42ae1d8c6968.jpeg)

**Comment by varvarasd** [comment] 2022-10-06 11:41
Ok. Is the mystery solved then?

**Comment by RaduGuce** [comment] 2022-10-06 11:43
If this is the way that dapp is working , yes mistery solved.

**Comment by varvarasd** [comment] 2022-10-06 11:49
Yes. I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-06 11:49 UTC
Labels: bug
