### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rockydawe** [ethernity-cloud/ethernity-staking-dapp#15] opened 2022-10-01 11:34 UTC
**Ethernity Cloud Staking login with Metamask**

'' Add suggested Token '' bug

**To Reproduce**

1. Go to (https://staking.ethernity.cloud/)
2. Click on 'Connect Wallet' 
3. It appears Automatticaly (Every time I try to connect) ''Add suggested Token tETNY ''( The token was already added before, and used in transactions. )
4. Sometimes Appears the token in adding list twice the same. ( See Photo Nr. 3)
5.  Either way if you press ''Cancel or Add Token'' logges you in. 
6. I tryed to Update the Metamask extension to the last version but it didn't solve the Problem, deleting the Cookies and browsing data from the Site, didn't helped at all.

**Expected behavior**

If the tETNY token was added before, this step is normally no longer required, and should not appear every time I try to log in.
I also spoked with Andrei Butoi and he suggested that deleting Cookies and browsing History will help if not I should create a Bug report. 

**Screenshots**
![1](https://user-images.githubusercontent.com/114801900/193406792-a2fc2279-8775-467f-86c3-c019ea69822b.JPG)
![2](https://user-images.githubusercontent.com/114801900/193406794-f3b674cf-2339-424e-bc64-499972a36259.JPG)
![3](https://user-images.githubusercontent.com/114801900/193406795-ef4ce52b-1765-474f-8066-55765969d0dd.jpg)
![4](https://user-images.githubusercontent.com/114801900/193406798-1f241ab4-58fc-46ed-9405-3eb300d27e1b.JPG)
![5](https://user-images.githubusercontent.com/114801900/193406802-25219559-df41-48cc-a5a3-17609e99c936.jpg)

**Desktop (please complete the following information):**
 
 - Browser Google Chrome 

**Additional context**

**Bug-bounty required information (optional)**
   fluerasdavid@yahoo.com

**Comment by varvarasd** [comment] 2022-10-04 09:31
Hi,
This is a limitation of MetaMask which doesn't allow us to check if the token's already added. This feature is available only in test net as it's not meant to be in production.
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 09:31 UTC
Labels: bug
