### ISSUE TITLE
PROPOSAL

### ISSUE THREAD

**Issue by MSorin5** [ethernity-cloud/ethernity-staking-dapp#46] opened 2022-10-04 10:49 UTC
It would be useful to simulate a shorter staking period (e.g. 1 day) during this test period in order to be able to see in the next steps after this staking period, if there are any problems and what are the next steps. What we are testing now is a large part of the operations but not all. What happens after the end of the staking period, i mean restake, unstake, what next steps...
ETNY tokens are automatically returned to your account at the end of the staking period or you have to unstake/restake...?

Please provide your email address if you wish to join the bug-bounty
sorinweb3@gmail.com

**Comment by varvarasd** [comment] 2022-10-04 11:45
Hi,
We are not taking any feature suggestions at this time as it's not a priority, however, thank you.
If you have any questions please join us on our [telegram](https://t.me/ethernitycloud) or [discord](https://discord.gg/W74JcFPGcb) channels as well as consult further the available documentation [here](https://docs.ethernity.cloud/staking-dapp/intro).

I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 11:45 UTC
Labels: bug
