### ISSUE TITLE
BUG : how to remove etni tokens from the node? if you accidentally sent them there, you can't connect the node with tokens, this is a bug in the test

### ISSUE THREAD

**Issue by Clubvp** [ethernity-cloud/ethernity-staking-dapp#25] opened 2022-10-02 07:57 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Bug-bounty required information (optional)**
Please provide your email address if you wish to join the bug-bounty

**Comment by Clubvp** [comment] 2022-10-02 07:58
how to remove etni tokens from the node? if you accidentally sent them there, you can't connect the node with tokens, this is a bug in the test

**Comment by varvarasd** [comment] 2022-10-03 11:44
Hi, this is not a bug. 
You can send the tokens from the node operator wallet to another wallet using metamask or use a new wallet with no ETNY tokens on it.
I will close this as not a bug.

**Closed as completed by varvarasd** 2022-10-03 11:44 UTC
Labels: bug
