### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Psyter** [ethernity-cloud/ethernity-staking-dapp#44] opened 2022-10-03 12:24 UTC
Unclear guide for staking (stated only where to get test tokens, not how to stake it). 
Unclear where to find node wallet address (not everyone is tech pro, users want just to choose a validator from the list). 
-
For newbies this staking mode is terrible, no one will stake their tokens. Will be massive dump.

**Comment by dim3nsi0n32** [comment] 2022-10-03 14:06
hi @Psyter this is not a bug.
Please find the documentation with pictures and a step-by-step explanation here: https://docs.ethernity.cloud/staking-dapp/base-stake and https://docs.ethernity.cloud/staking-dapp/extended-stake
How to get your node wallet address: https://docs.ethernity.cloud/staking-dapp/node-address-and-private-key
Also how to obtain tokens here: https://docs.ethernity.cloud/staking-dapp/open-beta-staking-dapp

**Comment by varvarasd** [comment] 2022-10-04 08:43
I am closing this as not a bug.
Thank you

**Closed as not planned by varvarasd** 2022-10-04 08:43 UTC
Labels: bug
